### PR TITLE
Cache

### LINKED ISSUE #30: Cache is not triggered
Reading the old code:
https://github.com/fastify/fastify-accepts-serializer/tree/v3.0.1

the cache behaviour can works if the users doesn't customize the `serializer` in the route options.

So the cache can be enabled and used from the `globalSerializerManager` when `reply.serializer` is empty

--

If I am not wrong, the cache in this plugin will never be fired. 

The main reason is that [```SerializerManager.expand```](https://github.com/fastify/fastify-accepts-serializer/blob/master/SerializerManager.js#L54-L56) always initialize a new instance and for the [```preHandler```](https://github.com/fastify/fastify-accepts-serializer/blob/master/index.js#L24) hook which call the ```SerializerManager.expand``` will lead to always having new cache for each route. 

As a result, calling same route multiple times or nesting will not trigger the cache.

_Originally posted by @climba03003 in https://github.com/fastify/fastify-accepts-serializer/issues/18#issuecomment-729910713_

### PR DESCRIPTION
**Pull request by simoneb**
Fixes #30 

Not an extremely elegant solution, but minimal code changes to make the cache work.

#### Checklist

- [X] run `npm run test` and `npm run benchmark`
- [X] tests and/or benchmarks are included
- [X] documentation is changed or added
- [X] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by mcollina — CHANGES_REQUESTED** [review]
Can you please add a test?

**Comment by simoneb** [comment]
> Can you please add a test?

I considered that, but then I figured that if we have 100 on tap it means that the cache is already tested.

If we want to test it explicitly instead, we may need to extract it so that it can be provided as a plugin option (can't think of any other way to test it directly). It's probably easy to do but it modifies the plugin interface so it also has to be documented.

wdyt?

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
this is ok, no worries

**Comment by climba03003** [comment]
here is my concern about your cache implementation.
https://github.com/fastify/fastify-accepts-serializer/issues/30#issuecomment-737578141

You can test your cache by specify two different route level serializer with same type but different behavior. and compare the expected result. if the results are the same they fail.

**Comment by Eomm** [comment]
I would agree with @climba03003 , but... the custom configuration per route is documented but not implemented!

This snippet doesn't work:

```
const fastify = require('fastify')()

fastify.register(require('./index'), {
  default: 'application/json'
})

fastify.get('/', {
  config: {
    serializer: {
      serializers: [{
        regex: /^application\/yaml$/,
        serializer: body => 'yaml-custom-no-global-one'
      }]
    }
  }
},
(req, reply) => { reply.send({ foo: 'bar' }) })

fastify.inject({
  url: '/',
  headers: {
    Accept: 'application/yaml'
  }
}, (_, res) => {
  console.log(res.statusCode)
  console.log(res.payload) // expected yaml-custom-no-global-one it is a json: {"foo":"bar"}
})
```

While, registering the plugin like this works as expected:

```
fastify.register(require('./index'), {
  serializers: [
    {
      regex: /^application\/yaml$/,
      serializer: body => 'yaml-global'
    }
  ],
  default: 'application/json'
})
```

The tests confirm this:

https://github.com/fastify/fastify-accepts-serializer/blob/c1df29368ed4ade1a1f50222c3dbc790d346bd5a/test/test.js#L255

Opening a new issue about it

File: SerializerManager.js [hunk 1]
```diff
@@ -14,15 +14,21 @@ class Serializer {
 class SerializerManager {
   constructor (configuration) {
     this.serializers = configuration.serializers
+    this.cache = configuration.cache
   }
 
   findSerializer (types) {
+    const cacheValue = this.cache[types]
+
+    if (cacheValue) return cacheValue
```
Comment (Eomm) [inline SerializerManager.js:23]: I agree that the `-100` coverage check the cache statement, I would just add a test that checks that the cache is filled and don't pollute (ex: 2 call different routes with same `Accept` expects only 1 entry in the cache).

Adding a test with an handler that check the `reply.serializer.cache` object (that should be accessible by the user) would add a really valuable check to avoid bad side cases when implementing the per-route-serialization

Comment (simoneb) [reply SerializerManager.js:23]: done

**Comment by simoneb** [comment]
@Eomm @climba03003 does this PR need further work?

**Review by Eomm — APPROVED** [review]
LGTM
